import type { SourceFileLabel, TableInsert } from "@/lib/types/database";

type MockQuestionSeed = {
  question: Omit<TableInsert<"questions">, "user_id" | "subject_id">;
  choices?: Array<Omit<TableInsert<"choices">, "question_id">>;
};

export const MOCK_SUBJECT = {
  name: "Mock Mathematics",
  color: "#e4bd62",
  icon: "Sigma",
};

export const MOCK_SOURCE_LABEL: SourceFileLabel = "other";

export const MOCK_QUESTION_SEEDS: MockQuestionSeed[] = [
  {
    question: {
      question_text: "Simplify: 3x + 5x - 2",
      type: "multiple_choice",
      topic: "Algebra",
      subtopic: "Combining Like Terms",
      difficulty: 1,
      answer: "8x - 2",
      explanation: "Combine the x terms first: 3x + 5x = 8x.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "6x - 2", is_correct: false },
      { text: "8x - 2", is_correct: true },
      { text: "8x + 2", is_correct: false },
      { text: "15x - 2", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "Solve for x: 2x + 7 = 19",
      type: "multiple_choice",
      topic: "Algebra",
      subtopic: "Linear Equations",
      difficulty: 1,
      answer: "6",
      explanation: "Subtract 7 from both sides, then divide by 2.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "5", is_correct: false },
      { text: "6", is_correct: true },
      { text: "7", is_correct: false },
      { text: "12", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "Factor completely: x^2 - 9",
      type: "multiple_choice",
      topic: "Algebra",
      subtopic: "Factoring",
      difficulty: 2,
      answer: "(x - 3)(x + 3)",
      explanation: "This is a difference of squares.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "(x - 9)(x + 1)", is_correct: false },
      { text: "(x - 3)(x + 3)", is_correct: true },
      { text: "(x - 3)^2", is_correct: false },
      { text: "Prime", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "What is the slope of the line passing through (2, 3) and (6, 11)?",
      type: "multiple_choice",
      topic: "Algebra",
      subtopic: "Slope",
      difficulty: 2,
      answer: "2",
      explanation: "Slope = (11 - 3) / (6 - 2) = 8 / 4 = 2.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "1", is_correct: false },
      { text: "2", is_correct: true },
      { text: "4", is_correct: false },
      { text: "8", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "Solve: x^2 - 5x + 6 = 0",
      type: "multiple_choice",
      topic: "Algebra",
      subtopic: "Quadratic Equations",
      difficulty: 3,
      answer: "x = 2 or x = 3",
      explanation: "Factor to (x - 2)(x - 3) = 0.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "x = 1 or x = 6", is_correct: false },
      { text: "x = 2 or x = 3", is_correct: true },
      { text: "x = -2 or x = -3", is_correct: false },
      { text: "x = 3 only", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "Find the value of 2^5 · 2^3.",
      type: "multiple_choice",
      topic: "Exponent Rules",
      subtopic: "Product Rule",
      difficulty: 1,
      answer: "256",
      explanation: "Add exponents: 2^(5+3) = 2^8 = 256.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "64", is_correct: false },
      { text: "128", is_correct: false },
      { text: "256", is_correct: true },
      { text: "512", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "Expand: (x + 4)^2",
      type: "multiple_choice",
      topic: "Algebra",
      subtopic: "Binomial Expansion",
      difficulty: 2,
      answer: "x^2 + 8x + 16",
      explanation: "Use (a+b)^2 = a^2 + 2ab + b^2.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "x^2 + 16", is_correct: false },
      { text: "x^2 + 8x + 16", is_correct: true },
      { text: "x^2 + 4x + 16", is_correct: false },
      { text: "x^2 + 8x + 8", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "If f(x) = 3x - 1, find f(5).",
      type: "multiple_choice",
      topic: "Functions",
      subtopic: "Function Evaluation",
      difficulty: 1,
      answer: "14",
      explanation: "Substitute 5 into the function: 3(5) - 1 = 14.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "12", is_correct: false },
      { text: "13", is_correct: false },
      { text: "14", is_correct: true },
      { text: "15", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "Write 0.00045 in scientific notation.",
      type: "multiple_choice",
      topic: "Scientific Notation",
      subtopic: "Conversions",
      difficulty: 2,
      answer: "4.5 × 10^-4",
      explanation: "Move the decimal 4 places to the right.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "4.5 × 10^4", is_correct: false },
      { text: "4.5 × 10^-4", is_correct: true },
      { text: "45 × 10^-5", is_correct: false },
      { text: "0.45 × 10^-3", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "A line has slope 3 and passes through (1, 2). What is its equation in slope-intercept form?",
      type: "multiple_choice",
      topic: "Algebra",
      subtopic: "Equation of a Line",
      difficulty: 3,
      answer: "y = 3x - 1",
      explanation: "Use y = mx + b and substitute the point to solve for b.",
      rubric_json: null,
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
    choices: [
      { text: "y = 3x + 1", is_correct: false },
      { text: "y = 3x - 1", is_correct: true },
      { text: "y = x + 3", is_correct: false },
      { text: "y = 2x + 1", is_correct: false },
    ],
  },
  {
    question: {
      question_text: "Explain how to solve the equation 4(x - 2) = 2x + 6 and give the final value of x.",
      type: "long_response",
      topic: "Algebra",
      subtopic: "Linear Equations",
      difficulty: 2,
      answer: "Distribute first to get 4x - 8 = 2x + 6. Subtract 2x from both sides to get 2x - 8 = 6, then add 8 to get 2x = 14, so x = 7.",
      explanation: "A full-credit response should show distribution and inverse operations clearly.",
      rubric_json: {
        criteria: [
          "Distributes correctly",
          "Uses inverse operations logically",
          "Finds x = 7",
        ],
      },
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
  },
  {
    question: {
      question_text: "Describe the difference between a linear function and a quadratic function, including how each appears on a graph.",
      type: "long_response",
      topic: "Functions",
      subtopic: "Function Families",
      difficulty: 3,
      answer: "A linear function has a constant rate of change and graphs as a straight line. A quadratic function has a changing rate of change and graphs as a parabola.",
      explanation: "Look for correct comparison of rate of change and graph shape.",
      rubric_json: {
        criteria: [
          "Mentions constant vs changing rate of change",
          "Identifies line vs parabola",
          "Uses accurate mathematical language",
        ],
      },
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
  },
  {
    question: {
      question_text: "A rectangle has length x + 3 and width x - 1. Write and simplify an expression for its area.",
      type: "long_response",
      topic: "Algebra",
      subtopic: "Polynomials",
      difficulty: 2,
      answer: "Area = (x + 3)(x - 1) = x^2 + 2x - 3.",
      explanation: "Multiply the binomials using distribution.",
      rubric_json: {
        criteria: [
          "Sets up the correct multiplication",
          "Expands correctly",
          "Simplifies to x^2 + 2x - 3",
        ],
      },
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
  },
  {
    question: {
      question_text: "Interpret what the slope and y-intercept mean in the equation y = 4x + 7.",
      type: "long_response",
      topic: "Algebra",
      subtopic: "Slope-Intercept Form",
      difficulty: 2,
      answer: "The slope is 4, meaning y increases by 4 for every 1-unit increase in x. The y-intercept is 7, meaning the line crosses the y-axis at (0, 7).",
      explanation: "A strong response explains both numbers in context.",
      rubric_json: {
        criteria: [
          "Correctly identifies slope as 4",
          "Correctly identifies y-intercept as 7",
          "Explains both in words",
        ],
      },
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
  },
  {
    question: {
      question_text: "Solve the system y = x + 1 and y = 2x - 3 and explain what the solution represents.",
      type: "long_response",
      topic: "Algebra",
      subtopic: "Systems of Equations",
      difficulty: 4,
      answer: "Set x + 1 = 2x - 3 to get x = 4. Substitute back to get y = 5. The solution (4, 5) is the point where the two lines intersect.",
      explanation: "Full credit includes algebra and interpretation.",
      rubric_json: {
        criteria: [
          "Equates the two expressions for y",
          "Finds x = 4 and y = 5",
          "Interprets the intersection point",
        ],
      },
      metadata_json: { mock: true },
      source_file_id: null,
      times_used: 0,
    },
  },
];
